# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'currency-converter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for currency-converter
  pod 'SnapKit'
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'RxDataSources'
  pod 'Alamofire', '5.2'
  pod 'SwiftMessages'
  
  target 'currency-converterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'currency-converterUITests' do
    # Pods for testing
  end

end
